# test:
#     path: /test/{age<\d+>?0}
#     controller: App\Controller\TestController::test
#     methods: [POST, GET]
#     host: localhost
#     schemes: [https, http]
   #  host: {subdomain}.monsite.com
   #  defaults:
   #    age: 0
   #  requirements: 
   #    age: \d+